import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import TanStackProvider from "@/provider/TanStackProvider";

const roboto = Montserrat({
  subsets: ["latin"],
  weight: ["500"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${roboto.className} antialiased`}
        >
          <TanStackProvider>
            {children}
          </TanStackProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
